package sideband

import chisel3._

/** UCIe Spec 6.1 */
class RegisterSidebandHeader extends Bundle {
  val srcid = SourceID()
  val rsvd_0 = Bits(2.W)

  /** Tag is a 5-bit field generated by the requester, and it must be unique for
    * all outstanding requests that require a completion. The original requester
    * uses the Tag to associate returning completions with the original request.
    */
  val tag = Bits(5.W)
  val be = Bits(8.W)
  val rsvd_1 = Bits(8.W)
  val ep = Bool()
  val opcode = PacketType()
}
